### ISSUE TITLE
截图会附带一行code

### ISSUE THREAD

**Issue by dongrentianyu** [tiddly-gittly/TiddlerScreenshot#2]
![image](https://github.com/tiddly-gittly/TiddlerScreenshot/assets/109711900/4eeca0a0-e2ec-41e3-bb01-6ffc79631dcc)

这个不知道是不是因为库克马插件影响了，还是我迁移插件过程中产生了丢失。

**Comment by oeyoews** [comment]
他这个应该是编译后的代码, 核心代码也就几行, 没必要使用modern, 这是之前写的, 想自己写的话, 可以参考参考 https://github.com/oeyoews/neotw/blob/main/plugins/oeyoews/tiddlywiki-tid2pdf/tiddlers/widget-png.js

**Comment by dongrentianyu** [comment]
感谢。但不知道你的插件写出来了没有？如果有更好的插件的话，这个插件就不用维护了。

**Comment by dongrentianyu** [comment]
嗯，应该是库克马的[插件](https://kookma.github.io/TW-Utility/)影响了。正常情况下details是不会展示。但因为他的插件中附带了一个复制按钮，就导致要多展示一行内容了。

现在应该是修复好了。

**Comment by linonetwo** [comment]
@oeyoews 你那个插件上 cpl 了吗，我只能搜到这个呀
