### ISSUE TITLE
截图会附带下拉框，如果是从下拉框里点的按钮

### ISSUE THREAD

**Issue by linonetwo** [tiddly-gittly/TiddlerScreenshot#4]
![Index-1691739496731](https://github.com/tiddly-gittly/TiddlerScreenshot/assets/3746270/d8a10196-c2af-48dd-9cbe-1adf747cd8da)

**Comment by dongrentianyu** [comment]
看样子像是解决了。先关闭了。没解决就再开启吧。

果然这种需要直接用到js的操作，对我来说还是难度太大了。这个插件估计就这样了，等有缘人再来加新功能或者修复吧。

而且也是无法导出notion-page里设置的背景图片，也搞了半天不知道怎么处理，目前就只有先这样了。

**Comment by Zacharia2** [comment]
因为是对条目进行的截图操作，就像拍照一样，所以当下的dom是什么状态它就会记录下来，然后转换为图片。

解决方法就是，放到工具栏即点即用，或是使用快捷键触发。
