### ISSUE TITLE
导出图片仍然会出现bug

### ISSUE THREAD

**Issue by dongrentianyu** [tiddly-gittly/TiddlerScreenshot#6]
应该还是库马克插件影响了。等未来再花时间排查吧。

**Comment by dongrentianyu** [comment]
![image](https://github.com/tiddly-gittly/TiddlerScreenshot/assets/109711900/7bafce30-d34e-4a3f-a412-b5bfcacc706a)

目前是需要只留一个条目在故事河中，不能有其他条目。

**Comment by Zacharia2** [comment]
```
{{ViewWidget||$:/core/templates/static-tiddler}}

就这个，可以修复图片的bug。

transclude 和view微件

$:/core/templates/html-tiddler


$:/core/templates/exporters/StaticRiver/Content


{{ViewWidget||$:/core/templates/exporters/StaticRiver}}
```

使用这些渲染好dom然后传递给插件即可解决。

**Comment by Zacharia2** [comment]
既然是使用Widget，可以使用参数传递给它，然后处理。这样整个流程都做好了。

**Comment by Zacharia2** [comment]
$:/core/modules/widgets/text.js

**Comment by Zacharia2** [comment]
无法解决，只能是在浏览器中正在显示的元素可以被渲染并保存，克隆的元素或独立于window对象的元素无法渲染并保存。

**Comment by dongrentianyu** [comment]
还有一点小瑕疵，但估计不是我能够解决的了，就先这样了。
